### ISSUE TITLE
completeness (name missing for example)

### ISSUE THREAD

**Issue by arthurpsmith** [ORCID/ORCID-Example-Client-Application#1]
I'm wondering if the orcid xml format is stable enough that we can expand on the client? I've been playing around with adding a more complete representation of what the orcid profile provides for the client "info" display, but if the xml format is still in flux then of course that will break quickly. In fact I notice right now the "full name" field seems to have changed (I switched to XPath //o:personal-details/o:credit-name for a default full name). Anyway, if there's any interest in seeing an expanded display of the data I could certainly post my modifications to share... Let me know!

**Comment by wjrsimpson** [comment]
Hi Arthur,

The schema used by the ORCID mock API is described [here](http://orcid.github.com/ORCID-Mock-API-Web-Application/schemas/orcid-message/1.0/).

This 'version' of the schema did change slightly as we updated the mock API (for example credit name). However, in future we will change the version number of the schema whenever any changes are made.

The real, non-mock version of ORCID (which is due to be released next week) will use version 1.0.1 of the schema. I believe the changes between 1.0 and 1.0.1 of the schema are minor and backwards compatible (though we have not specifically tested for backwards compatibility).

I've put version 1.0.1 of the schema [here](http://orcid.github.com/ORCID-Mock-API-Web-Application/schemas/orcid-message/1.0.1/) for you to preview. Please note that we will not be updating the mock API to use this version - only the real ORCID system will use the new version.

I'd certainly be interested in seeing your changes. Can set up a pull request in GitHub, so I can take a look at incorporating the changes?

Thanks,

Will

**Comment by arthurpsmith** [comment]
Thanks Will, I'll review those schema docs and probably make a few more 
tweaks today and tomorrow and try to get something up on github by the 
end of the day Friday...

```
     Arthur
```

**Comment by arthurpsmith** [comment]
Ok, I've posted a pull request for you (I hope) - I'm a little clunky with git/github still so if I did something wrong there please bear with me. Thanks.

**Comment by arthurpsmith** [comment]
Ok, I imported the formatter, that worked fine.

I only just realized I need to register (my version of) the client app 
on devsandbox. I just filled out the form for that today so I'll have to 
wait to get that registered to do further testing against that.

I was also looking at replacing the "josiah/carberry" default login in 
the example client with an actual user database - I hope that's not 
straying too far from what you'd intended with this client. I think a 
simple HSQL embedded database shows how things would work a bit more 
realistically. I have the login part of that working (with the same 
default user created automatically at server startup) but was going to 
add persistence next so you can register new users and try out 
multiple-user test cases. Would adding hibernate as well as hsql be 
overkill? Spring JDBC templates would probably be sufficient but I think 
a lot more people are familiar with hibernate in this sort of application.

```
Arthur
```

**Comment by wjrsimpson** [comment]
Hi Arthur,

I've sent your new your OAuth2 client credentials in an email from devsupport@orcid.org.

We are using Hibernate and HSQL (for unit tests) in the main ORCID code so those are great technology choices.

We've also used Freemarker templates (instead of JSP) with Spring MVC in the main ORCID code. So, if you are more comfortable with Freemarker, then it might be good to switch to that (but also happy if you prefer to continue with JSP).

I think a nice addition to the example app, would be the ability to update your profile from within JOPMTS. For example, add a new publication to your publication list. Any thoughts?

Will

**Comment by arthurpsmith** [comment]
Yup, got the credentials, they work, thanks!

No, I haven't used Freemarker (we used to use Apple's WebObjects and 
lately have been doing stuff with jruby and rails - it's a little 
complicated...) but JSP is fine and simple enough I think for people to 
extrapolate from.

Updating profile would definitely be a plus. I'll probably look at that 
after doing some more with searching.

```
 Arthur
```

**Comment by wjrsimpson** [comment]
Awesome. Thanks, Arthur.

W

**Comment by arthurpsmith** [comment]
This isn't really an open issue any more - so I'm closing it, thanks for the documentation. I did just post a new issue on another topic.
